In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("survey_results_public.csv", index_col="Respondent")
schema_df = pd.read_csv("survey_results_schema.csv", index_col="Column")

* ### logical operations: and: &, or: |, not: ~
* ### brackets are necessary when chaining logical operations

* ### filtering with index: cant set columns

In [6]:
df[(df["Hobbyist"] == "Yes") & (df["OpenSourcer"] == "Never")]

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
6,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Canada,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,28.0,Man,No,Straight / Heterosexual,East Asian,No,Too long,Neither easy nor difficult
15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
16,I am a developer by profession,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,United Kingdom,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,26.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82134,NaN,Yes,Never,NaN,NaN,China,No,I never completed any formal education,NaN,NaN,...,NaN,NaN,NaN,Man,No,NaN,NaN,NaN,NaN,NaN
83612,NaN,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Thailand,NaN,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,...,Not applicable - I did not use Stack Overflow ...,NaN,NaN,Woman,Yes,Gay or Lesbian,NaN,NaN,NaN,NaN
84299,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,...,Somewhat more welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85738,NaN,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Brazil,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Industry news about technologies you're intere...,15.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Too short,Easy
86638,NaN,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Australia,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",NaN,...,Just as welcome now as I felt last year,NaN,30.0,Man,No,Straight / Heterosexual,White or of European descent,Yes,Appropriate in length,Easy

* ### filtering with loc: can set columns

In [7]:
df.loc[~(df["Hobbyist"] == "Yes"), ["MainBranch", "OpenSourcer"]]

,MainBranch,OpenSourcer
Respondent,,
2,I am a student who is learning to code,Less than once per year
4,I am a developer by profession,Never
7,I am a developer by profession,Never
12,I am a student who is learning to code,Never
20,"I am not primarily a developer, but I write co...",Never
...,...,...
88076,NaN,Never
88212,NaN,Less than once per year
88601,NaN,Never
88802,NaN,Never
88816,NaN,Never

In [8]:
df.loc[df["ConvertedComp"] > 70000, ["ConvertedComp", "Country", "LanguageWorkedWith"]]

,ConvertedComp,Country,LanguageWorkedWith
Respondent,,,
6,366420.0,Canada,Java;R;SQL
9,95179.0,New Zealand,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;P...
13,90000.0,United States,Bash/Shell/PowerShell;HTML/CSS;JavaScript;PHP;...
16,455352.0,United Kingdom,Bash/Shell/PowerShell;C#;HTML/CSS;JavaScript;T...
22,103000.0,United States,Bash/Shell/PowerShell;C++;HTML/CSS;JavaScript;...
...,...,...,...
88876,180000.0,United States,Bash/Shell/PowerShell;C#;HTML/CSS;Java;Python;...
88877,2000000.0,United States,Bash/Shell/PowerShell;C;Clojure;HTML/CSS;Java;...
88878,130000.0,United States,HTML/CSS;JavaScript;Scala;TypeScript
88879,82488.0,Finland,Bash/Shell/PowerShell;C++;Python
88882,588012.0,Netherlands,C#;HTML/CSS;Java;JavaScript;PHP;Python

* ### isin

In [9]:
# pass list with isin-method
countries = ["United States", "United Kingdom", "India", "Canada", "Germany"]
df.loc[df["Country"].isin(countries), "Country"]

Respondent
1        United Kingdom
4         United States
6                Canada
8                 India
10                India
              ...
85642     United States
85961    United Kingdom
86012             India
88282     United States
88377            Canada
Name: Country, Length: 45008, dtype: object

* ### use methods on series datatype: str.contains

In [12]:
filt = df["LanguageWorkedWith"].str.contains("Python", na=False)
df.loc[filt, "LanguageWorkedWith"]

Respondent
1                          HTML/CSS;Java;JavaScript;Python
2                                      C++;HTML/CSS;Python
3                                                 HTML/CSS
4                                      C;C++;C#;Python;SQL
5              C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
                               ...
88377                        HTML/CSS;JavaScript;Other(s):
88601                                                  NaN
88802                                                  NaN
88816                                                  NaN
88863    Bash/Shell/PowerShell;HTML/CSS;Java;JavaScript...
Name: LanguageWorkedWith, Length: 88883, dtype: object